module:
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_filter: 0
  config_split: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  email_registration: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  link: 0
  menu_ui: 0
  node: 0
  options: 0
  path: 0
  redirect: 0
  smart_trim: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
profile: minimal
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
